services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"

  hbase:
    image: dajobe/hbase:latest
    container_name: hbase-distributed
    ports:
      - "16000:16000"  # HMaster
      - "16010:16010"  # HMaster UI
      - "16020:16020"  # RegionServer
    environment:
      - HBASE_CONF_hbase_security_authentication=simple
      - HBASE_CONF_hbase_security_authorization=true
      - HBASE_CONF_hbase_coprocessor_region_classes=org.apache.hadoop.hbase.security.access.AccessController
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
    volumes:
      - hbase-data:/hbase-data
      - ./hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    depends_on:
      - zookeeper

volumes:
  hbase-data: